In [459]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as opt

In [1]:
train_data = {
  'good': True,
  'bad': False,
  'happy': True,
  'sad': False,
  'not good': False,
  'not bad': True,
  'not happy': False,
  'not sad': True,
  'very good': True,
  'very bad': False,
  'very happy': True,
  'very sad': False,
  'i am happy': True,
  'this is good': True,
  'i am bad': False,
  'this is bad': False,
  'i am sad': False,
  'this is sad': False,
  'i am not happy': False,
  'this is not good': False,
  'i am not bad': True,
  'this is not sad': True,
  'i am very happy': True,
  'this is very good': True,
  'i am very bad': False,
  'this is very sad': False,
  'this is very happy': True,
  'i am good not bad': True,
  'this is good not bad': True,
  'i am bad not good': False,
  'i am good and happy': True,
  'this is not good and not happy': False,
  'i am not at all good': False,
  'i am not at all bad': True,
  'i am not at all happy': False,
  'this is not at all sad': True,
  'this is not at all happy': False,
  'i am good right now': True,
  'i am bad right now': False,
  'this is bad right now': False,
  'i am sad right now': False,
  'i was good earlier': True,
  'i was happy earlier': True,
  'i was bad earlier': False,
  'i was sad earlier': False,
  'i am very bad right now': False,
  'this is very good right now': True,
  'this is very sad right now': False,
  'this was bad earlier': False,
  'this was very good earlier': True,
  'this was very bad earlier': False,
  'this was very happy earlier': True,
  'this was very sad earlier': False,
  'i was good and not bad earlier': True,
  'i was not good and not happy earlier': False,
  'i am not at all bad or sad right now': True,
  'i am not at all good or happy right now': False,
  'this was not happy and not good earlier': False,
}

test_data = {
  'this is happy': True,
  'i am good': True,
  'this is not happy': False,
  'i am not good': False,
  'this is not bad': True,
  'i am not sad': True,
  'i am very good': True,
  'this is very bad': False,
  'i am very sad': False,
  'this is bad not good': False,
  'this is good and happy': True,
  'i am not good and not happy': False,
  'i am not at all sad': True,
  'this is not at all good': False,
  'this is not at all bad': True,
  'this is good right now': True,
  'this is sad right now': False,
  'this is very bad right now': False,
  'this was good earlier': True,
  'i was not happy and not good earlier': False,
}

In [461]:
vocab = []
for k, v in train_data.items():
    v = k.split()
    for word in v:
        if word not in vocab:
            vocab.append(word)
vocab_size = len(vocab)

In [462]:
def word_to_idx(word):
    return vocab.index(word)

In [463]:
def idx_to_word(idx):
    return vocab[idx]

In [464]:
def OneHotEncode(word):
    v = np.zeros(vocab_size)
    v[word_to_idx(word)] = 1
    return v

In [465]:
sentence_max_length = 10
def createInputs(inputs):
    v = []
    w = []
    for word in inputs.split():
        v.append(OneHotEncode(word))
    for i in range(sentence_max_length - len(v)):
        v.append(np.zeros(vocab_size))
    w.append(v)
    return w

In [466]:
w = createInputs('i am happy') # Result can be different
w

[[array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.]),
  array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.]),
  array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.])]]

In [467]:
v = torch.tensor(w[0])
v = v.to(torch.float32)
v.shape

torch.Size([10, 18])

In [7]:
import pandas as pd
train_df = pd.read_csv('data/train_data.csv')
dict = train_df.set_index('X').T.to_dict('list')

In [21]:
import string
dct = {}
for k, v in dict.items():
    label = str(v).translate(str.maketrans('', '', string.punctuation))
    if label == 'True':
        b = True
    if label == 'False':
        b = False
    dct[k] = b
dct

{'good': True,
 'bad': False,
 'happy': True,
 'sad': False,
 'not good': False,
 'not bad': True,
 'not happy': False,
 'not sad': True,
 'very good': True,
 'very bad': False,
 'very happy': True,
 'very sad': False,
 'i am happy': True,
 'this is good': True,
 'i am bad': False,
 'this is bad': False,
 'i am sad': False,
 'this is sad': False,
 'i am not happy': False,
 'this is not good': False,
 'i am not bad': True,
 'this is not sad': True,
 'i am very happy': True,
 'this is very good': True,
 'i am very bad': False,
 'this is very sad': False,
 'this is very happy': True,
 'i am good not bad': True,
 'this is good not bad': True,
 'i am bad not good': False,
 'i am good and happy': True,
 'this is not good and not happy': False,
 'i am not at all good': False,
 'i am not at all bad': True,
 'i am not at all happy': False,
 'this is not at all sad': True,
 'this is not at all happy': False,
 'i am good right now': True,
 'i am bad right now': False,
 'this is bad right now': Fa

In [468]:
def z_score(matrix):
    mean = torch.mean(matrix, dim = 1, keepdim = True)
    std = torch.std(matrix, dim = 1, keepdim = True)
    z_score_vector = (matrix-mean)/std
    return z_score_vector

def self_attention(mask, Q, K, V):
    att = (Q @ K.T + mask)/np.sqrt(Q.shape[0])
    return (torch.softmax(att, dim = 0) @ V)

In [469]:
class transformer():
    def __init__(self, input_size, output_size, hidden_size = 64):
        # That is the number of heads
        self.n_heads = 2
        # Here we can define matrices in pytorch with require_grad = True
        # Initialize matrices for self-attention layer
        self.Wq = torch.empty(0, input_size)
        self.Wk = torch.empty(0, input_size)
        self.Wv = torch.empty(0, input_size)
        for i in range(self.n_heads):
            Wq = torch.rand(hidden_size, input_size)/1000
            self.Wq = torch.cat((self.Wq, Wq), dim = 0)
            Wk = torch.rand(hidden_size, input_size)/1000
            self.Wk = torch.cat((self.Wk, Wk), dim = 0)
            Wv = torch.rand(hidden_size, input_size)/1000
            self.Wv = torch.cat((self.Wv, Wv), dim = 0)
        
        self.Wq.requires_grad = True
        self.Wk.requires_grad = True
        self.Wv.requires_grad = True

        # Initialize the matrix Wo for the projection of the multi head layer output
        self.Wo = torch.rand(hidden_size, self.n_heads * hidden_size)/1000
        self.Wo.requires_grad = True
        # Create the mask matrix with upper part is -infinity
        # and other entries are 0
        # First we create a matrix filled with - infinity at all entries
        matrix = torch.full((self.n_heads*hidden_size, self.n_heads * hidden_size), -float('inf'))
        # triu = triangular upper part, we want to fill in upper part with - infinity
        matrix = torch.triu(matrix)
        # Replace the diagonal by 0
        matrix = matrix.fill_diagonal_(0)
        self.mask = matrix
        # That is for the positional encoding
        self.n = 10000


        # Dimension matching layer for the layer norm
        # This layer norm is after self-attention layer
        self.Wnorm_self = torch.rand(hidden_size, input_size)/1000
        self.Wnorm_self.requires_grad = True
        self.bnorm_self = torch.zeros((hidden_size,1), requires_grad=True)
        self.gamma_self = torch.rand((sentence_max_length,hidden_size))/1000
        self.gamma_self.requires_grad = True
        self.beta_self = torch.zeros((hidden_size,1), requires_grad=True)

        # Initialize matrices for feed-forward layer
        self.Wf = torch.rand(output_size, hidden_size)/1000
        self.Wf.requires_grad = True
        self.bf = torch.zeros((output_size,1), requires_grad=True)

        # Initialize parameters for layer normalization after feedforward layer
        self.Wnorm_feed = torch.rand(output_size, hidden_size)/1000
        self.Wnorm_feed.requires_grad = True
        self.bnorm_feed = torch.rand((output_size,1), requires_grad=True)
        self.gamma_feed = torch.rand((hidden_size,1))/1000
        self.gamma_feed.requires_grad = True
        self.beta_feed = torch.zeros((output_size,1), requires_grad=True)    
    
    # Positional encoding for the whole sentence
    def positional_encoding(self, inputs):
        pos_encoding = torch.empty(inputs.shape[0],0)
        iter = inputs.shape[1]
        for k in range(iter):
            d = inputs.shape[0]
            pos = torch.zeros((d,1))
            for i in range(d):
                if i % 2 == 0:
                    pos[i] = np.sin(k/(self.n**(i/d)))
                if i % 2 == 1:
                    pos[i] = np.cos(k/(self.n**((i-1)/d)))
            v_pos = inputs[:, k].reshape(-1,1) + pos
            pos_encoding = torch.cat((pos_encoding, v_pos), dim = 1)
        return pos_encoding
    
    # Multi-head attention
    def multi_head_attention(self, inputs):
        q = self.Wq @ inputs
        k = self.Wk @ inputs
        v = self.Wv @ inputs
        attention = self_attention(self.mask, q, k, v)
        output = self.Wo @ attention
        return output
        
    # Layer norm after self-attention layer
    def layer_norm_self_attention(self, previous_layer_outputs, inputs):
        inputs_matching = self.Wnorm_self @ inputs + self.bnorm_self
        vector = previous_layer_outputs + inputs_matching
        z_score_vector = z_score(vector)
        next_inputs = z_score_vector @ self.gamma_self + self.beta_self
        return next_inputs

    # Feed forward after layer norm
    def feed_forward(self, inputs):
        output = self.Wf @ inputs + self.bf
        output = torch.relu(output)
        return output
        
    # Layer norm after feed_forward
    def layer_norm_feed_forward(self, previous_layer_outputs, inputs):
        intputs_matching = self.Wnorm_feed @ inputs + self.bnorm_feed
        vector = previous_layer_outputs + intputs_matching
        z_score_vector = z_score(vector)
        next_inputs = z_score_vector @ self.gamma_feed + self.beta_feed
        return next_inputs
    
    def forward(self, inputs):
        # Inputs is a whole sentence at a time
        # Inputs will be a list with only one element
        # And this element is the matrix representation of the sentence
        # The matrix consists of row vectors, each row is a word embedding
        torch_inputs = torch.tensor(inputs[0])
        torch_inputs = torch_inputs.T
        torch_inputs = torch_inputs.to(torch.float32)
        pos_inputs = self.positional_encoding(torch_inputs)
        output_self_attention = self.multi_head_attention(pos_inputs)
        output_layer_norm_self = self.layer_norm_self_attention(output_self_attention, pos_inputs)
        output_feed_forward = self.feed_forward(output_layer_norm_self)
        output_layer_norm_feed = self.layer_norm_feed_forward(output_feed_forward, output_layer_norm_self)
        y_pred = torch.softmax(output_layer_norm_feed, dim = 0)
        return y_pred
    
    def backward(self, y_pred, y_true, learning_rate = 0.03):
        loss = nn.CrossEntropyLoss()
        optimizer = opt.SGD([self.Wq, self.Wk, self.Wv, self.Wo, 
                             self.Wnorm_self, self.bnorm_self, self.gamma_self, self.beta_self, 
                             self.Wf, self.bf, 
                             self.Wnorm_feed, self.bnorm_feed, self.gamma_feed, self.beta_feed],
                             lr = learning_rate)
        L = loss(y_pred, y_true)
        L.backward()
        optimizer.step()
    
    def process(self, data, run_backward = False):
        items = list(data.items())
        accuracy = 0
        for x, y_true in items:
            # Transform a sentence to a matrix
            inputs = createInputs(x)
            probs = self.forward(inputs)
            # True label
            true_index = int(y_true)  
            # Accuracy
            accuracy += int(torch.argmax(probs) == true_index) 
            if run_backward:
                y_true_torch = torch.zeros((2,1))
                y_true_torch[true_index] = 1
                L = self.loss(probs, y_true_torch)
                self.optimizer.zero_grad()
                L.backward()
                self.optimizer.step()
         # Accuracy 
        return float(accuracy/len(data))
    
    def fit(self, data, max_iter = 201, learning_rate = 0.001):
        self.loss = nn.BCEWithLogitsLoss()
        self.optimizer = opt.SGD([self.Wq, self.Wk, self.Wv, self.Wo, 
                                self.Wnorm_self, self.bnorm_self, self.gamma_self, self.beta_self, 
                                self.Wf, self.bf, 
                                self.Wnorm_feed, self.bnorm_feed, self.gamma_feed, self.beta_feed],
                                lr = learning_rate)
        for i in range(max_iter):
            accuracy = self.process(data, run_backward=True)
            if(i % 20 == 0):
                print(f"Step: {i}")
                print(f"accuracy for training data: {accuracy}")
    
    def predict(self, data):
        return self.process(data, run_backward=False)

In [470]:
model = transformer(vocab_size, 2)
model.fit(train_data)

Step: 0
accuracy for training data: 0.39655172413793105
Step: 100
accuracy for training data: 0.5517241379310345
Step: 200
accuracy for training data: 0.5517241379310345
Step: 300
accuracy for training data: 0.8620689655172413
Step: 400
accuracy for training data: 0.8620689655172413
Step: 500
accuracy for training data: 0.8620689655172413
Step: 600
accuracy for training data: 0.8620689655172413
Step: 700
accuracy for training data: 0.8620689655172413
Step: 800
accuracy for training data: 0.8620689655172413
Step: 900
accuracy for training data: 0.8620689655172413
Step: 1000
accuracy for training data: 0.8620689655172413


In [471]:
model.predict(test_data)

0.8